### ISSUE TITLE
Create CAP / VIVO-ISF Mapping

### ISSUE THREAD

**Issue by azaroth42** [sul-dlss/cap-vivo-mapper#1]
- [x] Understand CAP data
- [x] Understand VIVO-ISF ontology
- [x] Produce mapping of Person information, including roles and relationships to other people
- [x] Hand craft example mapping for discussion, suggest using M. Dumontier

Due 8/21/2015 for discussion at Cornell

**Comment by dazza-codes** [comment]
This pilot work is complete.
